"""Refit the published operational snow hindcasts from their annual inputs.

    python PIPELINES/verify_snow_forecast_region.py

Requires a regional gauges.json regenerated by build_snow_forecast_region.py
after operational_inputs were added. This checks the statistical hindcast;
it does not independently reproduce ERA5-Land extraction or discharge QC.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
import sys

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]

REPORT = ROOT / "PUBLISHED/data/case-studies/snow-forecast/region/gauges.json"
FIELDS = ["water_year", "mean_swe_mm", "april_september_mean_discharge_m3s"]
METRICS = ("skill_raw", "skill_corrected", "rmse_raw", "rmse_corrected",
           "rmse_climatology", "bias_raw", "bias_corrected")


def refit(frame):
    """Independent implementation of the expanding-window operational forecast."""
    history = []
    for year, row in frame.iterrows():
        if year < 1971:
            continue
        earlier = frame.loc[frame.index < year]
        if len(earlier) < 15:
            continue
        matrix = np.column_stack((np.ones(len(earlier)), earlier["mean_swe_mm"].to_numpy()))
        target = earlier["april_september_mean_discharge_m3s"].to_numpy()
        intercept, slope = np.linalg.lstsq(matrix, target, rcond=None)[0]
        raw = intercept + slope * row["mean_swe_mm"]
        correction = np.mean((target - matrix @ np.array([intercept, slope]))[-10:])
        history.append((year, row["april_september_mean_discharge_m3s"], raw,
                        raw + correction, target[-30:].mean()))

    def score(rows):
        if not rows:
            return None
        array = np.asarray(rows, dtype=float)
        observed, raw, corrected, baseline = (array[:, i] for i in (1, 2, 3, 4))
        reference_error = np.square(observed - baseline).sum()
        return {"years": [int(array[0, 0]), int(array[-1, 0])], "n": len(rows),
                "skill_raw": float(1 - np.square(observed - raw).sum() / reference_error),
                "skill_corrected": float(1 - np.square(observed - corrected).sum() / reference_error),
                "rmse_raw": float(np.sqrt(np.square(observed - raw).mean())),
                "rmse_corrected": float(np.sqrt(np.square(observed - corrected).mean())),
                "rmse_climatology": float(np.sqrt(np.square(observed - baseline).mean())),
                "bias_raw": float(np.mean(raw - observed)),
                "bias_corrected": float(np.mean(corrected - observed))}

    recent = [row for row in history if row[0] >= 1996]
    return {"all": score(history), "recent": score(recent) if len(recent) >= 8 else None}


def verify(report):
    issues = 0
    for gauge in report["gauges"]:
        for month, record in gauge["issue"].items():
            label = f"gauge {gauge['code']} issue {month}"
            inputs = record.get("operational_inputs")
            if not inputs or inputs.get("fields") != FIELDS:
                raise ValueError(f"{label}: full-precision operational inputs are absent")
            frame = pd.DataFrame(inputs["rows"], columns=FIELDS).set_index("water_year")
            if frame.empty or frame.index.has_duplicates or not frame.index.is_monotonic_increasing:
                raise ValueError(f"{label}: years are empty, duplicated or unsorted")
            if frame.isna().any().any():
                raise ValueError(f"{label}: operational input contains a missing value")
            actual = refit(frame)
            saved = record["operational"]["meanSWE"]
            for period in ("all", "recent"):
                expected, rebuilt = saved[period], actual[period]
                if (expected is None) != (rebuilt is None):
                    raise ValueError(f"{label} {period}: score availability differs")
                if expected is None:
                    continue
                if (expected["years"], expected["n"]) != (rebuilt["years"], rebuilt["n"]):
                    raise ValueError(f"{label} {period}: year range or sample count differs")
                for metric in METRICS:
                    if not math.isclose(expected[metric], rebuilt[metric], rel_tol=1e-9, abs_tol=1e-9):
                        raise ValueError(f"{label} {period}: {metric} differs")
            issues += 1
    return len(report["gauges"]), issues


if __name__ == "__main__":
    if len(sys.argv) > 2:
        raise SystemExit("Usage: python verify-snow-forecast-region.py [gauges.json]")
    report_path = Path(sys.argv[1]) if len(sys.argv) == 2 else Path(__file__).with_name("gauges.json")
    if len(sys.argv) == 1 and not report_path.exists():
        report_path = REPORT
    gauges, issues = verify(json.loads(report_path.read_text()))
    print(f"PASS: refitted operational hindcasts for {gauges} gauges and {issues} issue records")
