import React, { useEffect, useState } from 'react';

const ROOT = '/data/case-studies/';
const fmt = (v, n = 2) => v == null ? '—' : Number(v).toLocaleString('en', { maximumFractionDigits: n });
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const MODEL_NAMES = { seasonal_climatology: 'Seasonal baseline', physical_bucket: 'Snow & soil bucket', random_forest: 'Random forest', bayesian_linear: 'Bayesian linear model', climate: 'Climate only', climate_plus_snow: 'Climate + snow', climate_plus_snow40: 'Climate + conservative snow', climate_plus_swe: 'Climate + modelled SWE' };

export function Readiness({ environment }) {
  const [selected, setSelected] = useState(4);
  const [build, setBuild] = useState(null);
  useEffect(()=>{
    let active=true;
    const refresh=()=>fetch(`${ROOT}pipeline-status.json`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(r=>{if(active)setBuild(r);}).catch(()=>{});
    refresh();const timer=setInterval(refresh,15000);
    return()=>{active=false;clearInterval(timer);};
  },[]);
  if (!environment) return null;
  const { readiness, freshness } = environment;
  return <section className="cs-readiness" aria-label="Data and modelling readiness">
    <div className="cs-section-head"><div><span className="cs-eyebrow">EVIDENCE READINESS / PUBLISHED CHECKS</span><h2>Available does not yet mean ready.</h2></div><span className={`cs-readiness-status ${readiness.overall}`}>Modelling release: {readiness.operational_ready ? 'ready' : 'blocked'}</span></div>
    <div className="cs-process" role="group" aria-label="Readiness checks">{readiness.steps.map((step, i) => <button key={step.label} className={step.status} aria-pressed={selected === i} onClick={() => setSelected(i)}><span>{i + 1}</span><strong>{step.label}</strong><small>{step.status === 'green' ? 'Check complete' : step.status === 'amber' ? 'Limitations remain' : 'Action needed'}</small></button>)}</div>
    <p className="cs-readiness-detail"><strong>{readiness.steps[selected].label}:</strong> {readiness.steps[selected].reason}</p>
    <p className="cs-note">{readiness.meaning} Latest ERA5 month: <strong>{freshness.era5_latest_available}</strong>. Observed discharge still ends in 2017.</p>
    <details><summary>Data dates and refresh progress</summary><div className="cs-table-wrap"><table><thead><tr><th>Dataset</th><th>Latest available input</th><th>Meaning</th></tr></thead><tbody>
      <tr><td>ERA5-Land</td><td>{freshness.era5_latest_available}</td><td>Monthly forcing and unverified model continuation</td></tr>
      {Object.entries(freshness.modis_latest_available).map(([key,value])=><tr key={key}><td>MODIS {key.toUpperCase()}</td><td>{value}</td><td>Composite start date; product coverage differs</td></tr>)}
      <tr><td>Esri / Impact Observatory land cover</td><td>{environment.profile_metadata.landcover_years[1]}</td><td>Annual classification</td></tr><tr><td>Observed discharge</td><td>2017-12</td><td>No recent gauge verification supplied</td></tr>
    </tbody></table></div>{build&&<p>Last pipeline run: <strong>{build.status}</strong> · {build.completed}/{build.total} processing stages complete{build.current_step?` · ${build.current_step}`:''}. {build.finished_at?`Finished ${build.finished_at.slice(0,10)}.`:''} This is processing progress; scientific readiness is shown above. Reload the page after a completed refresh to load its new results.</p>}<p>Refresh command: <code>npm run cases:update</code>. The downloaded reports retain their input hashes and original observation dates.</p></details>
  </section>;
}

function ScoreTable({ models, annual = false }) {
  return <div className="cs-table-wrap"><table><thead><tr><th>Model</th><th>Test observations</th><th>RMSE ({annual ? 'million m³' : 'm³/s'})</th><th>Bias</th><th>NSE</th><th>KGE</th></tr></thead><tbody>{models.map(r => <tr key={r.model}><td>{MODEL_NAMES[r.model] || r.model}</td><td>{r.scores.n}</td><td>{fmt(r.scores.rmse)}</td><td>{fmt(r.scores.bias)}</td><td>{fmt(r.scores.nse,3)}</td><td>{fmt(r.scores.kge,3)}</td></tr>)}</tbody></table></div>;
}

function Scatter({ rows }) {
  const points = rows.filter(r => r.air != null && r.lst != null);
  if (points.length < 3) return <p>Insufficient overlapping air and surface-temperature values.</p>;
  const xm = points.reduce((s,r) => s+r.air,0)/points.length, ym = points.reduce((s,r) => s+r.lst,0)/points.length;
  const xx=points.reduce((s,r)=>s+(r.air-xm)**2,0), yy=points.reduce((s,r)=>s+(r.lst-ym)**2,0), xy=points.reduce((s,r)=>s+(r.air-xm)*(r.lst-ym),0);
  const slope=xy/xx, intercept=ym-slope*xm, corr=xy/Math.sqrt(xx*yy);
  const minX=Math.floor(Math.min(...points.map(r=>r.air))-2), maxX=Math.ceil(Math.max(...points.map(r=>r.air))+2);
  const minY=Math.floor(Math.min(...points.map(r=>r.lst))-2), maxY=Math.ceil(Math.max(...points.map(r=>r.lst))+2);
  const x=v=>55+(v-minX)/(maxX-minX)*635, y=v=>260-(v-minY)/(maxY-minY)*235;
  return <figure className="cs-chart"><figcaption>How warm is the surface compared with the air?</figcaption><svg viewBox="0 0 760 310" role="img" aria-label="Monthly daytime MODIS land-surface temperature versus ERA5 air temperature, with descriptive linear fit">
    {[0,1,2,3,4].map(i=><g key={i}><line className="cs-grid" x1="55" x2="690" y1={y(minY+(maxY-minY)*i/4)} y2={y(minY+(maxY-minY)*i/4)}/><text x="45" y={y(minY+(maxY-minY)*i/4)+4} textAnchor="end">{fmt(minY+(maxY-minY)*i/4,0)}</text><text x={x(minX+(maxX-minX)*i/4)} y="281" textAnchor="middle">{fmt(minX+(maxX-minX)*i/4,0)}</text></g>)}
    {points.map(r=><circle key={r.period} cx={x(r.air)} cy={y(r.lst)} r="3" fill={['06','07','08'].includes(r.period.slice(-2))?'#edb06c':'#58c9e5'} opacity=".55"><title>{r.period}: air {fmt(r.air)} °C, surface {fmt(r.lst)} °C</title></circle>)}
    <line x1={x(minX)} x2={x(maxX)} y1={y(slope*minX+intercept)} y2={y(slope*maxX+intercept)} stroke="#dce8ed" strokeWidth="1.5"/>
    <text x="375" y="305" textAnchor="middle">ERA5 air temperature · °C</text><text x="8" y="15">MODIS surface · °C</text>
  </svg><p className="cs-note">{points.length} monthly pairs. Surface ≈ {fmt(slope)} × air + {fmt(intercept)} °C; r = {fmt(corr,3)}. Orange points are June–August. This seasonal association is not air-temperature validation: MODIS measures clear-sky surface skin temperature.</p></figure>;
}

function SnowEvidence({ advanced, Chart }) {
  const [sensor,setSensor]=useState('combined'),[band,setBand]=useState('all'),[view,setView]=useState('snow');
  const rows=advanced.snow_monthly.filter(r=>r.sensor===sensor&&r.elevation_band===band);
  const years=[...new Set(rows.map(r=>r.period.slice(0,4)))];
  const lookup=new Map(rows.map(r=>[r.period,r]));
  return <section className="cs-panel" id="snow-evidence"><div className="cs-section-head"><div><span className="cs-eyebrow">SATELLITE SNOW / DAILY QUALITY PRESERVED</span><h2>Where and when does snow persist?</h2></div><div className="cs-controls"><label>Sensor<select aria-label="Snow sensor" value={sensor} onChange={e=>setSensor(e.target.value)}><option value="combined">Terra + Aqua, same day</option><option value="terra">Terra</option><option value="aqua">Aqua</option></select></label><label>Elevation<select aria-label="Snow elevation" value={band} onChange={e=>setBand(e.target.value)}>{[['all','Whole candidate basin'],['below1500','Below 1,500 m'],['1500to2500','1,500–2,500 m'],['2500to3500','2,500–3,500 m'],['above3500','Above 3,500 m']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></div>
    <p>Snow stores winter water for later release. Clouds hide part of that store. We retain those gaps and show the amount of usable observation alongside snow cover.</p>
    <div className="cs-switch"><button aria-pressed={view==='snow'} onClick={()=>setView('snow')}>Snow-covered area</button><button aria-pressed={view==='coverage'} onClick={()=>setView('coverage')}>Observation coverage</button></div>
    <Chart rows={rows} unit="%" title={view==='snow'?'Monthly snow cover among valid pixels':'Mean daily area with usable observations'} fields={view==='snow'?[{key:'snow_cover_percent',label:'Positive screened NDSI',color:'#58c9e5'},{key:'snow40_cover_percent',label:'Conservative threshold',color:'#baa5ef',dashed:true}]:[{key:'mean_valid_area_percent',label:'Valid observed area',color:'#9bcd86'}]}/>
    <details open><summary>Snow persistence calendar</summary><div className="cs-snow-calendar"><span>Year</span>{MONTHS.map(m=><span key={m}>{m}</span>)}{years.map(year=><React.Fragment key={year}><strong>{year}</strong>{MONTHS.map((m,i)=>{const p=`${year}-${String(i+1).padStart(2,'0')}`,r=lookup.get(p),v=r?.snow_cover_percent;return <div key={p} className="cs-snow-cell" title={`${p}: ${v==null?'insufficient coverage':fmt(v)+'% snow'}; ${r?.eligible_days||0} qualifying days`} style={{background:v==null?'#293844':`hsl(195 65% ${18+v*.53}%)`}}><span>{v==null?'—':fmt(v,0)}</span></div>;})}</React.Fragment>)}</div></details>
    <p className="cs-note">Brighter blue means more snow; grey means insufficient clear-sky information. Daily valid area ≥70%; monthly mean ≥10 qualifying days. Same-day combination uses Terra first and Aqua where Terra is masked; no neighbouring dates are filled.</p>
    <details><summary>Checks against observed station snow days</summary><div className="cs-table-wrap"><table><thead><tr><th>Station</th><th>Sensor</th><th>Paired months</th><th>Months ≥70% observed</th><th>Mean daily coverage</th><th>Compatible snow-day bounds</th></tr></thead><tbody>{advanced.snow_station_summary.map(r=><tr key={r.station+r.sensor}><td>{r.station}</td><td>{r.sensor}</td><td>{r.months}</td><td>{r.months_70pct_observed}</td><td>{fmt(r.mean_coverage_percent)}%</td><td>{fmt(r.compatible_percent)}%</td></tr>)}</tbody></table></div><p>Observed snow-day counts are checked against the satellite minimum (detected snowy days) and maximum (that count plus unobserved days). Compatibility is not daily classification accuracy, and wide cloudy-month bounds are weak evidence.</p></details>
  </section>;
}

function ElevationEvidence({ environment, Chart }) {
  const [variable,setVariable]=useState('area_km2'),[year,setYear]=useState(String(environment.profile_metadata.landcover_years[1]));
  const metadata={area_km2:['Area','km²'],temperature_c:['Air temperature','°C'],precipitation_mm_year:['Annual precipitation','mm/year'],runoff_generated_mcm_year:['Modelled runoff generated','million m³/year'],cumulative_runoff_above_mcm_year:['Cumulative modelled runoff from above','million m³/year']};
  const rows=environment.elevation_profiles.map(r=>({...Object.fromEntries(Object.entries(r).map(([k,v])=>[k,Number(v)])),label:`${r.minimum_m} m`}));
  const classes=environment.profile_metadata.classes,colors=environment.profile_metadata.class_colors;
  const land=environment.landcover_elevation.filter(r=>String(r.year)===year&&r.valid_class==='True');
  return <section className="cs-panel" id="elevation-evidence"><div className="cs-section-head"><div><span className="cs-eyebrow">THE MOUNTAIN PROFILE / 250 M ELEVATION BANDS</span><h2>What changes as we climb?</h2></div><div className="cs-controls"><label>Profile<select aria-label="Elevation profile variable" value={variable} onChange={e=>setVariable(e.target.value)}>{Object.entries(metadata).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></label></div></div>
    <Chart rows={rows} fields={[{key:variable,label:metadata[variable][0],color:'#58c9e5'}]} unit={metadata[variable][1]} title={`${metadata[variable][0]} by elevation`}/>
    <p className="cs-note">Elevation and area use Copernicus DEM at 30 m. Climate is a 2010–2024 summary of coarse ERA5 cells intersecting each band, not 250 m climate downscaling. Cumulative runoff sums local modelled generation from high to low elevation; it is not routed or observed discharge.</p>
    <div className="cs-section-head"><h3>Land cover along the mountain</h3><label>Esri / IO year <select aria-label="Land cover year" value={year} onChange={e=>setYear(e.target.value)}>{Array.from({length:environment.profile_metadata.landcover_years[1]-2017+1},(_,i)=>2017+i).map(y=><option key={y}>{y}</option>)}</select></label></div>
    <div className="cs-land-profile">{rows.map(r=>{const values=land.filter(v=>Number(v.minimum_m)===r.minimum_m);const total=values.reduce((s,v)=>s+Number(v.area_km2),0);return <div key={r.minimum_m}><span>{r.minimum_m}–{r.maximum_m} m</span><div className="cs-stacked">{values.map(v=><span key={v.class_code} style={{width:`${Number(v.area_km2)/total*100}%`,background:colors[v.class_code]}} title={`${v.class}: ${fmt(v.area_km2)} km² (${fmt(Number(v.area_km2)/total*100,1)}%)`}/>)}</div><small>{fmt(total,0)} km²</small></div>;})}</div>
    <div className="cs-legend">{Object.entries(classes).filter(([id])=>id!=='10').map(([id,name])=><span key={id}><i style={{background:colors[id],height:9,width:9}}/>{name}</span>)}</div>
    <p className="cs-note">Areas come from 10 m classifications. Bars show shares of valid mapped classes within each elevation band. Class changes may include mapping errors; local land-cover accuracy still needs independent labelled samples.</p>
  </section>;
}

function SurfaceEvidence({ environment, Chart }) {
  const [variable,setVariable]=useState('temperature');
  const lookup=Object.fromEntries(['lst','et','albedo'].map(product=>[product,new Map(environment.surface_monthly.filter(r=>r.product===product).map(r=>[r.period,r]))]));
  const rows=environment.energy_monthly.map(r=>({period:r.period,air:Number(r.temperature_c),lst:lookup.lst.get(r.period)?.value??null,modis_et:lookup.et.get(r.period)?.value??null,albedo:lookup.albedo.get(r.period)?.value??null,
    model_et:Number(r.evapotranspiration_mm),solar:Number(r.solar_down_wm2),net:Number(r.net_solar_wm2),lst_coverage:lookup.lst.get(r.period)?.mean_valid_area_percent??null,et_coverage:lookup.et.get(r.period)?.mean_valid_area_percent??null}));
  const settings={temperature:{unit:'°C',title:'Surface and air temperature',fields:[{key:'air',label:'ERA5 2 m air temperature',color:'#58c9e5'},{key:'lst',label:'MODIS daytime surface temperature',color:'#edb06c'}],note:'The ground can be much warmer than the air. MODIS sees clear-sky daytime surface temperature; ERA5 represents monthly mean air temperature.'},
    et:{unit:'mm/month',title:'Water returned to the atmosphere',fields:[{key:'model_et',label:'ERA5 basin modelled ET',color:'#58c9e5'},{key:'modis_et',label:'MOD16 valid terrestrial footprint',color:'#9bcd86'}],note:'ET is evaporation plus plant transpiration. MOD16 excludes large non-vegetated, water and snow areas; its changing valid footprint is not a basin-wide measurement. Composite totals are allocated by overlapping days; incomplete months remain gaps.'},
    radiation:{unit:'W/m²',title:'Solar energy at the surface',fields:[{key:'solar',label:'Incoming solar',color:'#edb06c'},{key:'net',label:'Net solar after reflection',color:'#baa5ef'}],note:'Incoming sunshine supplies energy. Net solar radiation subtracts reflected sunlight. These are ERA5 model estimates converted from monthly energy totals to mean power.'},
    albedo:{unit:'fraction',title:'How much sunlight does the surface reflect?',fields:[{key:'albedo',label:'MODIS black-sky shortwave albedo',color:'#baa5ef'}],note:'Albedo runs from 0 (absorbs light) to 1 (reflects light). Snow often raises it. These daily estimates use overlapping 16-day windows, so neighbouring dates are not independent.'},
    coverage:{unit:'%',title:'How much area did MODIS represent?',fields:[{key:'lst_coverage',label:'LST valid footprint',color:'#edb06c'},{key:'et_coverage',label:'ET valid footprint',color:'#9bcd86'}],note:'Low coverage means the mean represents only a small observed portion of the basin. Similar-looking series with different footprints are not interchangeable.'}};
  const selected=settings[variable];
  return <section className="cs-panel"><div className="cs-section-head"><div><span className="cs-eyebrow">SURFACE ENERGY & WATER</span><h2>Sunlight, heat and evaporation.</h2></div><div className="cs-controls"><label>View<select aria-label="Surface energy variable" value={variable} onChange={e=>setVariable(e.target.value)}>{[['temperature','Surface and air temperature'],['radiation','Solar radiation'],['et','Evapotranspiration'],['albedo','Albedo'],['coverage','Observation footprints']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div></div>
    <Chart rows={rows} fields={selected.fields} unit={selected.unit} title={selected.title}/><p className="cs-note">{selected.note}</p><details><summary>Explore the linear surface–air relationship</summary><Scatter rows={rows}/></details>
  </section>;
}

function ModellingEvidence({ environment, advanced, Chart }) {
  const [phase,setPhase]=useState('held_out'),[model,setModel]=useState('physical_bucket');
  const rows=environment.model_series.filter(r=>phase==='all'||r.phase===phase);
  return <section className="cs-panel" id="modelling-evidence"><div className="cs-section-head"><div><span className="cs-eyebrow">MODEL COMPARISON / 2001–2010 TRAINING · 2011–2017 TEST</span><h2>Can a model explain unseen years?</h2></div><div className="cs-controls"><label>Model<select aria-label="Monthly model" value={model} onChange={e=>setModel(e.target.value)}>{Object.entries(MODEL_NAMES).slice(0,4).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Period<select aria-label="Model period" value={phase} onChange={e=>setPhase(e.target.value)}><option value="held_out">Held-out test</option><option value="training">Training</option><option value="unverified_continuation">Unverified continuation</option><option value="all">Full record</option></select></label></div></div>
    <div className="cs-model-explain"><div><strong>Physical</strong><p>Rain and melt enter a soil store. Evaporation removes water; quick flow and slow drainage reach the outlet.</p></div><div><strong>Machine learning</strong><p>A small random forest learns recurring relationships. It cannot reliably extrapolate beyond its training conditions.</p></div><div><strong>Bayesian</strong><p>A linear model combines explicit prior assumptions with observations, producing a range of possible future observations.</p></div></div>
    <Chart rows={rows} unit="m³/s" title={phase==='unverified_continuation'?'Experimental continuation — no observed discharge after 2017':'Monthly discharge comparison'} fields={[{key:'observed_cms',label:'Screened gauge observation',color:'#58c9e5'},{key:model,label:MODEL_NAMES[model],color:'#edb06c'},...(model==='bayesian_linear'?[{key:'bayesian_lower95',label:'Lower 95% predictive limit',color:'#baa5ef',dashed:true},{key:'bayesian_upper95',label:'Upper 95% predictive limit',color:'#baa5ef',dashed:true}]:[])]}/>
    <ScoreTable models={environment.monthly_models}/><p className="cs-note">Lower RMSE means smaller typical errors. NSE = 1 is perfect; NSE = 0 matches the observed test mean. Compare against the seasonal baseline as well. All displayed models use the same held-out months. A good fit does not resolve the gauge-location uncertainty.</p>
    <details><summary>Bayesian uncertainty and physical checks</summary><p>The nominal 95% Bayesian predictive interval contains {fmt(environment.bayesian_interval_check.held_out_coverage*100,1)}% of held-out observations. Mean width: {fmt(environment.bayesian_interval_check.mean_width_cms)} m³/s. {environment.bayesian_interval_check.note}</p><p>Physical monthly water-budget residual: {environment.physical_mass_balance_max_abs_mm.toExponential(2)} mm. Conserving water is necessary, but does not prove that simulated snow, soil or glacier contributions are correct.</p><ul>{environment.model_limits.map(v=><li key={v}>{v}</li>)}</ul></details>
    <h3>Which inputs does the random forest rely on?</h3><div className="cs-importance">{environment.feature_importance.map(r=>{const maximum=Math.max(1,...environment.feature_importance.map(v=>Math.abs(v.mean_rmse_increase_cms)));return <div key={r.variable}><span>{r.variable.replaceAll('_',' ')}</span><div><i style={{width:`${Math.abs(r.mean_rmse_increase_cms)/maximum*100}%`,background:r.mean_rmse_increase_cms>=0?'#edb06c':'#baa5ef'}}/></div><strong>{fmt(r.mean_rmse_increase_cms)} m³/s</strong></div>;})}</div><p className="cs-note">Bars show how test error changes when whole years of one input are rearranged. Larger positive values indicate greater predictive reliance; negative values mean that rearrangement helped. Calendar features repeat every year, so this test cannot assess their importance. Correlated inputs and a short test period prevent causal conclusions.</p>
    {advanced&&<details><summary>Separate April 1 seasonal-volume experiment</summary><p>{advanced.seasonal_flow.protocol}</p><p>Matched snow cohort: {advanced.seasonal_flow.training_years.length} training and {advanced.seasonal_flow.test_years.length} test years. Status: {advanced.seasonal_flow.status.replaceAll('_',' ')}.</p>{advanced.seasonal_flow.models.length>0?<ScoreTable models={advanced.seasonal_flow.models} annual/>:<p>Too few qualifying years to fit and score this specification under the strict snow-coverage rule.</p>}<p>Climate-only cohort: a separate experiment with all complete seasonal-flow years.</p><ScoreTable models={advanced.climate_only_flow.models} annual/></details>}
  </section>;
}

export default function AdvancedCaseStudy({ advanced, environment, Chart }) {
  return <>
    <section className="cs-panel"><span className="cs-eyebrow">RELATED PSKEM RESEARCH</span><h2>Sabitov’s glaciated-watershed study.</h2><p>The literature review compares the thesis’s four model specifications and reported metrics, and identifies what is needed for a reproducible comparison with this study.</p><a href="/data/case-studies/sabitov-2018-review.md" download>Read the results review and replication priorities ↗</a></section>
    {advanced&&<section className="cs-panel"><span className="cs-eyebrow">HISTORICAL VALIDATION / TESTED CORRECTIONS</span><h2>Does correcting the bias help later years?</h2><p>Offsets and precipitation ratios are learned from earlier observations, then frozen before the later-year test. The table retains cases where correction makes the result worse.</p><div className="cs-table-wrap"><table><thead><tr><th>Station</th><th>Product</th><th>Variable</th><th>Test period</th><th>Raw RMSE</th><th>Corrected RMSE</th><th>Anomaly r</th></tr></thead><tbody>{advanced.climate_validation.filter(r=>r.correction).map(r=><tr key={r.station+r.product+r.variable}><td>{r.station}</td><td>{r.product}</td><td>{r.variable==='air_temperature_mean'?'Temperature · °C':'Precipitation · mm'}</td><td>{r.correction.test_start}–{r.correction.test_end}</td><td>{fmt(r.correction.raw_test.rmse)}</td><td>{fmt(r.correction.corrected_test.rmse)}</td><td>{fmt(r.anomaly_scores.r,3)}</td></tr>)}</tbody></table></div><p className="cs-note">Anomaly correlation removes the expected monthly seasonal cycle using training data only. CHIRTS is a daily minimum/maximum midrange proxy and has no overlap with the later-year correction test. Station contribution to blended products remains unaudited.</p></section>}
    {advanced&&<SnowEvidence advanced={advanced} Chart={Chart}/>}
    {environment&&<><ElevationEvidence environment={environment} Chart={Chart}/><SurfaceEvidence environment={environment} Chart={Chart}/><ModellingEvidence environment={environment} advanced={advanced} Chart={Chart}/></>}
    {advanced&&<section className="cs-panel"><span className="cs-eyebrow">CHARVAK / INDEPENDENT SENSOR CHECK</span><h2>Watch the shoreline, keep the missing months.</h2><Chart rows={advanced.reservoir.monthly.map(r=>({...r,water_area_km2:r.eligible?r.water_area_km2:null,sentinel:advanced.reservoir.sentinel_check.pairs.find(p=>p.period===r.period)?.predicted??null}))} fields={[{key:'water_area_km2',label:'JRC / Landsat water detection',color:'#58c9e5'},{key:'sentinel',label:'Sentinel-2 best-coverage scene',color:'#edb06c'}]} unit="km²" title="Monthly detected water extent"/><p>{advanced.reservoir.eligible_months} of {advanced.reservoir.total_months} JRC months pass the 95% valid-area rule. The independent-sensor check has {advanced.reservoir.sentinel_check.scores.n} paired months and RMSE {fmt(advanced.reservoir.sentinel_check.scores.rmse)} km².</p><p className="cs-note">{advanced.reservoir.sentinel_check.limits} Water area is not water volume; absolute storage requires independently constrained levels and an elevation–volume curve.</p></section>}
    <section className="cs-panel cs-advanced-downloads"><h2>Download the evidence behind the charts.</h2>{[['chirchik-environment-study.md','Terrain, energy and modelling report'],['chirchik-scientific-atlas.pdf','Scientific figure atlas · PDF'],['chirchik-analysis.xlsx','Supporting analysis workbook'],['pskem-study-map.png','Study map · PNG'],['chirchik-deep-study.md','Deep validation report'],['advanced-validation.json','Validation results and fitted corrections'],['environment-modelling.json','Profiles, models, uncertainty and readiness'],['monthly-model-predictions.csv','Monthly model predictions'],['elevation-profiles.csv','Elevation profiles'],['landcover-elevation.csv','Land cover by elevation'],['snow-monthly.csv','Snow and coverage by month'],['surface-monthly.csv','Surface energy summaries'],['charvak-cross-sensor-pairs.csv','Charvak sensor comparisons']].map(([file,label])=><a href={ROOT+file} download key={file}>{label} ↗</a>)}</section>
  </>;
}
