import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './dynamic-atlas.css';

const fmt = v => v == null || v === '' ? '—' : Number(v).toLocaleString(undefined, { maximumFractionDigits: 3 });
const json = async url => { const r = await fetch(url, { cache: 'no-store' }); if (!r.ok) throw Error(`Could not load data (${r.status})`); return r.json(); };
const native = r => [r.grid, r.native_scale_m && `${fmt(r.native_scale_m)} m`, r.native_arcsec && `${r.native_arcsec}″`].filter(Boolean).join(' · ');

function Results({ data }) {
  const [batch, setBatch] = useState(null), [error, setError] = useState(''), [column, setColumn] = useState('run_mm_syr');
  useEffect(() => { json(`${data.download_base}batch.json`).then(setBatch).catch(e => setError(e.message)); }, [data.download_base]);
  if (error) return <p role="alert">{error}</p>;
  if (!batch) return <p role="status">Loading the saved basin results…</p>;
  const a = batch.attributes.find(x => x.column === column) || batch.attributes[0];
  const f = data.families.find(x => x.family === a.surrogate_family);
  return <>
    <label className="field">Attribute <select aria-label="Attribute" value={a.column} onChange={e => setColumn(e.target.value)}>{batch.attributes.map(x => <option key={x.column} value={x.column}>{x.column} · {x.label}</option>)}</select></label>
    <p>{a.label} · {a.spatial_support === 'u' ? 'Upstream contributing units' : a.spatial_support === 's' ? 'Local sub-basin' : `Support code ${a.spatial_support}`}. {a.surrogate_method || a.surrogate_pending_reason || a.review_required}</p>
    <p><strong>Saved period:</strong> {f.used_period}. Surrogate fidelity: {f.fidelity.replaceAll('_', ' ')}. Values below are saved estimates; empty values remain missing.</p>
    <div className="table-scroll"><table><thead><tr><th>HYBAS_ID</th><th>Original<br/><small>{a.units}</small></th><th>Candidate<br/><small>{a.units}</small></th><th>Substitute<br/><small>{f.units.surrogate}</small></th><th>Substitute in atlas units</th><th>Valid spatial coverage</th></tr></thead>
      <tbody>{batch.basin_ids.map(id => { const s = a.surrogate_values?.[id]; const v = s?.raw_value; return <tr key={id}><th>{id}{id === '4121289400' ? ' · outlet' : ''}</th><td>{fmt(a.reference_values[id])}</td><td>{fmt(a.candidate_values?.[id]?.raw_value)}</td><td>{fmt(v)}</td><td>{f.units.convertible && v != null ? fmt(v * f.units.factor) : '—'}</td><td>{s?.coverage_fraction == null ? '—' : `${fmt(s.coverage_fraction * 100)}%`}</td></tr>; })}</tbody></table></div>
    <p className="muted">Spatial coverage describes the saved reduction support. It does not measure cloud-free days, temporal completeness, or accuracy. Differences across vintages and methods are diagnostics, not reproduction tests.</p>
  </>;
}

function App() {
  const [data, setData] = useState(null), [error, setError] = useState(''), [query, setQuery] = useState(''), [theme, setTheme] = useState('all'), [status, setStatus] = useState('all');
  const load = () => { setError(''); json('/data/atlas/dynamic-atlas.json').then(setData).catch(e => setError(e.message)); };
  useEffect(load, []);
  const checks = Object.fromEntries((data?.availability?.sources || []).map(s => [s.asset, s]));
  const families = data?.families.filter(f => (theme === 'all' || f.category === theme) && (status === 'all' || (status === 'gaps' ? f.missing > 0 : f.acquisition === status)) && `${f.family} ${f.label} ${f.original.dataset} ${f.assets.join(' ')} ${f.columns.join(' ')}`.toLowerCase().includes(query.toLowerCase())) || [];
  return <main>
    <nav><a href="/">UzGeoData</a><div><a href="/roadmap.html">Atlas roadmap</a><a href="/surrogates.html">Scientific methods</a></div></nav>
    <header><p className="eyebrow">PSKEM PILOT / EARTH ENGINE / LIVING GEODATABASE</p><h1>From a static atlas<br/>to dated basin evidence.</h1><p className="intro">What we fetched, what it substitutes, and what can change over time. A dedicated audit of the HydroATLAS pilot and its path to regular updates.</p><div className="jump"><a href="#coverage">Thematic coverage ↓</a><a href="#results">See basin values ↓</a><a href="#refresh">Update pathway ↓</a></div></header>
    {error ? <div role="alert"><p>{error}</p><button onClick={load}>Try again</button></div> : !data ? <p role="status">Loading the pilot audit…</p> : <>
      <div className="stats">{[[data.summary.basin_count, 'level-12 pilot basins'], [data.summary.attribute_count, 'original atlas attributes'], [data.summary.candidate_attributes, 'recalculated candidates'], [data.summary.surrogate_attributes, 'substitute attributes'], [data.summary.attributes_without_any_estimate, 'still without an estimate']].map(([n, label]) => <div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div>
      <section className="callout"><h2>The pilot has results. Scheduled updates are not implemented yet.</h2><p>{data.scope} The saved run contains {fmt(data.summary.reference_nonmissing)} populated original values across {fmt(data.summary.reference_records)} records and {fmt(data.summary.surrogate_nonmissing)} populated substitute values. {data.summary.earth_engine_attributes} candidate/substitute attributes use Earth Engine; the remainder use local/provider archives.</p><p>Most saved results are climatologies or fixed epochs. Re-running the current extraction reuses its cache and fixed periods. A new retrieval date alone does not make a new observation. No attribute has passed independent scientific reproduction review.</p><p className="stamp">Evidence run: <code>{data.run_id}</code></p></section>
      <section id="coverage"><p className="eyebrow">01 / THE THEMATIC CROSSWALK</p><h2>All six HydroATLAS themes, accounted for.</h2><p><a href="https://www.hydrosheds.org/hydroatlas">HydroATLAS</a> supplies 56 variables and 281 attributes. This project uses BasinATLAS geometry and identifiers as the spatial reference, with separate candidate and substitute values.</p>
        <div className="legend"><span className="candidate">Recalculated candidate</span><span className="surrogate">Substitute estimate</span><span className="missing">No new estimate</span></div>
        <div className="themes">{data.themes.map(t => <div key={t.category}><div className="theme-label"><strong>{t.category}</strong><span>{t.candidates} / {t.surrogates} / {t.missing} · {t.attributes} total</span></div><div className="bar" role="img" aria-label={`${t.category}: ${t.candidates} candidates, ${t.surrogates} substitutes, ${t.missing} missing`}>{['candidates', 'surrogates', 'missing'].map(k => <span key={k} className={k} style={{ width: `${100 * t[k] / t.attributes}%` }}/>)}</div></div>)}</div>
        <div className="filters"><label>Search sources or attributes<input value={query} onChange={e => setQuery(e.target.value)} placeholder="e.g. snow, pre_mm, TerraClimate"/></label><label>Theme<select aria-label="Theme" value={theme} onChange={e => setTheme(e.target.value)}><option value="all">All themes</option>{data.themes.map(t => <option key={t.category}>{t.category}</option>)}</select></label><label>Evidence<select aria-label="Evidence" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All evidence</option><option>Earth Engine</option><option>Local/provider archive</option><option value="gaps">Remaining gaps</option></select></label></div>
        <p aria-live="polite">{families.length} of {data.families.length} variable families</p>
        <div className="families">{families.map(f => <details key={f.family}><summary><code>{f.family}</code><strong>{f.label}</strong><span>{f.candidates} candidate · {f.surrogates} substitute · {f.missing} gap</span></summary><div className="family-content"><div className="compare"><div><h3>HydroATLAS reference</h3><p><a href={f.original.catalogue_url}>{f.original.dataset}</a></p><p><strong>Native resolution:</strong> {f.original_native}</p><p><strong>Period:</strong> {f.original.period}</p></div><div><h3>{f.acquisition}</h3><p><a href={f.source.catalogue_url}>{f.source.name}</a></p><p><strong>Native resolution:</strong> {native(f.resolution)}</p><p><strong>Actually used:</strong> {f.used_period}</p></div></div>
          <p><strong>Processing:</strong> {f.resolution.processing_grid_arcsec} arc-seconds · {f.resolution.resampling}. {f.resolution.support_change}</p><p><strong>Source cadence:</strong> {f.cadence}. <strong>Proposed refresh:</strong> {f.refresh_policy}</p>
          {f.assets.map(asset => { const c = checks[asset]; return <p className="asset" key={asset}><code>{asset}</code><br/><small>{c ? `Live audit: ${c.status}${c.latest_image_date ? ` · latest image timestamp ${c.latest_image_date.slice(0, 10)}` : ''}${c.error ? ` · ${c.error}` : ''}` : 'No live Earth Engine check for this asset'}</small></p>; })}
          <p><strong>Retrieval evidence:</strong> {f.retrieved_at || 'Date not recorded at this source-lock level'}{f.sha256 && <> · SHA-256 <code>{f.sha256}</code></>}</p>
          <p>{f.notes.join(' ')}</p>{f.pending && <p><strong>Gap:</strong> {typeof f.pending === 'string' ? f.pending : JSON.stringify(f.pending)}</p>}<p><strong>Atlas columns:</strong> <code>{f.columns.join(', ')}</code></p>
        </div></details>)}</div>
      </section>
      <section className="callout"><h2>Three different meanings of resolution.</h2><div className="three"><div><h3>Native source</h3><p>The source determines information content: TerraClimate is ~4.6 km; ERA5-Land ~11.1 km in the EE catalogue. Resampling cannot create local detail.</p></div><div><h3>Processing grid</h3><p>The pilot uses 15 arc-seconds, approximately 345 × 464 m at 42° N. Glacier and protected-area polygons are rasterized at 30 m then aggregated; lake intersections use vector geometry.</p></div><div><h3>Published support</h3><p>Values belong to complete level-12 basins or upstream contributing units. Twelve calendar-month climatologies are not twelve dated monthly observations.</p></div></div></section>
      <section id="results"><p className="eyebrow">02 / ACTUAL SAVED VALUES</p><h2>Inspect the results for every pilot basin.</h2><Results data={data}/></section>
      <section id="refresh"><p className="eyebrow">03 / FROM REPEATABLE TO UPDATABLE</p><h2>Refresh by source cadence, with a dated record.</h2><p>TerraClimate and ERA5-Land can supply monthly fields; MODIS supplies daily snow observations. Their existing atlas builders collapse those observations into fixed normals. A dynamic adapter must retain dates, completeness and revisions before publishing new basin rows.</p>
        <p><a href="https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_TERRACLIMATE">TerraClimate documentation</a> · <a href="https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_LAND_MONTHLY_AGGR">ERA5-Land documentation</a> · <a href="https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MYD10A1">MODIS snow documentation</a></p>
        <div className="proposal-grid">{data.proposals.map(p => <article key={p.asset}><span className="tag">PROPOSED ADAPTER</span><h3><a href={p.url}>{p.name}</a></h3><p>{p.native} · {p.cadence}</p><p>Atlas families: {p.families}</p><p>{p.policy}</p><small>{checks[p.asset] ? `Live access: ${checks[p.asset].status}; ${checks[p.asset].latest_image_date?.slice(0, 10) || 'no image date'}` : 'Not checked live'}. No substitute values from this adapter in the saved batch.</small></article>)}</div>
        <details className="audit"><summary>Live Earth Engine audit · {data.availability?.checked_at || 'not run'}</summary><p>{data.availability?.scope || 'Run the source audit to check access.'}</p><p>Latest image timestamps describe catalogue records, not guaranteed complete periods. A successful sample proves limited pilot access, not scientific suitability or full coverage.</p><div className="table-scroll"><table><thead><tr><th>Asset</th><th>Status</th><th>First date</th><th>Latest date</th><th>Sample evidence</th></tr></thead><tbody>{data.availability?.sources.map(s => <tr key={s.asset}><th><code>{s.asset}</code></th><td>{s.status}</td><td>{s.first_image_date?.slice(0, 10) || '—'}</td><td>{s.latest_image_date?.slice(0, 10) || '—'}</td><td>{s.error || (s.pilot_feature_count != null ? `${s.pilot_feature_count} pilot features` : `${s.valid_sample_pixels} pixels · ${s.sample_band} at ${fmt(s.probe_scale_m)} m`)}</td></tr>)}</tbody></table></div></details>
      </section>
      <section><p className="eyebrow">04 / GEODATABASE CONTRACT</p><h2>Keep the reference. Append the observations.</h2><p>Use versioned basin geometry and HYBAS_ID as the join. Store each value with attribute code, method version, source release, observation start/end, temporal statistic, units, native resolution, processing grid, spatial support, valid coverage, retrieval date and run ID. Keep original, candidate and substitute as explicit value roles.</p><ol><li>Check source availability and select complete periods. Archive metadata and source IDs.</li><li>Extract missing periods, recording QA masks and valid-day or valid-pixel denominators. Reprocess recent provisional periods as revisions.</li><li>Validate units, ranges, support and completeness; compare climate and flow with independent observations.</li><li>Append an immutable run and update the latest approved view. A scheduler and dated atlas adapters remain future implementation work.</li></ol><p>The current downloads are ready for staging and inspection. A production time-series schema and automated updates still need implementation; the current observations CSV deliberately leaves observation year empty for climatologies.</p>
      <div className="downloads"><a href={`${data.download_base}observations.csv`} download>5,620 observation records ↓</a><a href={`${data.download_base}pilot-basins.geojson`} download>Pilot geometry ↓</a><a href="/data/atlas/dynamic-atlas-crosswalk.csv" download>Thematic crosswalk ↓</a><a href="/data/atlas/dynamic-atlas.json" download>Full audit JSON ↓</a><a href={`${data.download_base}source-lock.json`} download>Source lock ↓</a><a href="/data/atlas/dynamic-atlas-methods.md" download>Refresh commands & contract ↓</a></div></section>
      <footer>Run {data.run_id} · Inventory generated {data.generated_at.slice(0, 10)} · <a href="/surrogates.html">Detailed scientific record</a></footer>
    </>}
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
