import React, { useEffect, useState } from 'react';

const BASE='/data/case-studies/';
const fmt=(v,n=2)=>v==null?'—':Number(v).toLocaleString('en',{maximumFractionDigits:n});
const COLORS={observed:'#dce8ed',m1:'#58c9e5',m2:'#a9cd7e',m3:'#baa5ef',m4:'#edb06c'};
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export default function SabitovCaseStudy({ Chart }) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[view,setView]=useState('flow'),[scenarioModel,setScenarioModel]=useState('m4');
  useEffect(()=>{let active=true;fetch(`${BASE}sabitov-methods.json`).then(r=>{if(!r.ok)throw Error(`Thesis-method evidence unavailable (${r.status}).`);return r.json();}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  if(error)return <section className="cs-panel" id="sabitov-methods"><h2>Sabitov methodology</h2><p role="alert">{error}</p></section>;
  if(!data)return <section className="cs-panel" id="sabitov-methods" aria-busy="true"><p>Loading the thesis-method comparison…</p></section>;
  const held=data.monthly_predictions.filter(r=>r.period>='2011-01'&&r.period<='2017-12');
  const fields=[{key:'observed',label:'Observed',color:COLORS.observed},...data.models.map(m=>({key:m.key,label:m.key.toUpperCase(),color:COLORS[m.key]}))];
  const fdc=Array.from({length:99},(_,i)=>({label:`${i+1}%`,...Object.fromEntries(['Observed','m1','m2','m3','m4'].map(key=>[key==='Observed'?'observed':key,data.flow_duration.find(r=>r.series===key&&r.exceedance_percent===i+1)?.discharge_cms]))}));
  const components=data.components.filter(r=>r.period>='2011-01'&&r.period<='2017-12');
  const scenarios=data.climate_scenarios.filter(r=>r.model===scenarioModel);
  const scenarioRows=MONTHS.map((label,i)=>({label,...Object.fromEntries(scenarios.map((s,j)=>[`s${j}`,s.monthly[i].discharge_cms]))}));
  return <section className="cs-panel" id="sabitov-methods">
    <div className="cs-section-head"><div><span className="cs-eyebrow">FULL THESIS / SABITOV 2018</span><h2>Test the mountain-water processes.</h2></div><a href={`${BASE}sabitov-2018-review.md`} download>Full methodology review ↗</a></div>
    <p>The local thesis adds a daily question to our monthly study: when precipitation arrives, how much stays as snow, enters the soil, feeds groundwater or reaches the river? Four implemented adaptations test elevation zones, glacier melt and curve-number runoff.</p>
    <div className="cs-evidence-strip"><span><strong>{fmt(data.inputs.rows,0)}</strong> real daily weather records</span><span><strong>{fmt(data.inputs.zones.reduce((s,z)=>s+z.glacier_area_km2,0))} km²</strong> mapped historical glacier area</span><span><strong>{fmt(data.split.held_out_days,0)}</strong> held-out discharge days</span></div>
    <p className="cs-note">Warm-up: {data.split.warmup}. Calibration: {data.split.training}. Independent temporal test: {data.split.held_out}. These are adaptations using ERA5 and a provisional catchment; they do not reproduce the thesis’s exact inputs or scores.</p>
    {data.physical_readiness&&<p className="cs-note cs-pending"><strong>Physical validation: unresolved.</strong> {data.physical_readiness.reason} {Object.entries(data.physical_readiness.exhaustion_dates).map(([k,v])=>`${k.toUpperCase()}: ${v}`).join(' · ')}. Ice-depth sensitivities are available below.</p>}
    <div className="cs-table-wrap"><table><thead><tr><th>Daily model</th><th>Daily RMSE · m³/s</th><th>Daily NSE</th><th>Monthly NSE</th><th>Modelled ice share</th></tr></thead><tbody>
      <tr><td>Training seasonal baseline</td><td>{fmt(data.baseline_daily_scores.rmse)}</td><td>{fmt(data.baseline_daily_scores.nse,3)}</td><td>—</td><td>—</td></tr>
      {data.models.map(m=><tr key={m.key}><td>{m.label}</td><td>{fmt(m.daily_scores.rmse)}</td><td>{fmt(m.daily_scores.nse,3)}</td><td>{fmt(m.monthly_scores.nse,3)}</td><td>{fmt(100*m.held_out_ice_fraction_of_modelled_flow)}%</td></tr>)}
    </tbody></table></div>
    <p className="cs-note">RMSE is the typical error size: lower is better. NSE measures agreement with the observed variation: 1 is perfect, 0 equals an observed-mean benchmark. Ice share is modelled direct drainage under assumed ice storage, not a measured contribution.</p>
    {data.paired_year_bootstrap&&<details><summary>Does the improvement persist across different years?</summary><p>{data.bootstrap_note}</p><div className="cs-table-wrap"><table><thead><tr><th>Model</th><th>RMSE difference · m³/s</th><th>Paired year-bootstrap 95% interval</th></tr></thead><tbody>{data.paired_year_bootstrap.map(r=><tr key={r.model}><td>{r.model.toUpperCase()}</td><td>{fmt(r.rmse_difference_vs_baseline_cms)}</td><td>{fmt(r.lower95)} to {fmt(r.upper95)}</td></tr>)}</tbody></table></div></details>}
    <div className="cs-controls"><label>Hydrology chart<select aria-label="Thesis hydrology chart" value={view} onChange={e=>setView(e.target.value)}><option value="flow">Held-out monthly hydrograph</option><option value="duration">Flow-duration curve</option><option value="paths">Runoff pathways</option><option value="snow">Snow process check</option><option value="et">Evapotranspiration process check</option></select></label></div>
    {view==='flow'&&<Chart rows={held} fields={fields} unit="m³/s" title="Do the models reproduce the seasonal rise and fall?"/>}
    {view==='duration'&&<><Chart rows={fdc} fields={fields} unit="m³/s" title="How often is this discharge exceeded?"/><p className="cs-note">Left: uncommon high flows. Right: persistent low flows. Observed Q90 is {fmt(data.low_flow.q90_cms)} m³/s and Q95 is {fmt(data.low_flow.q95_cms)} m³/s. Q90/Q50 = {fmt(data.low_flow.q90_q50_proxy,3)} describes low-flow persistence; it is not a measured groundwater fraction.</p></>}
    {view==='paths'&&<><Chart rows={components} fields={[{key:'baseflow_mm',label:'Groundwater release',color:COLORS.m2},{key:'quickflow_mm',label:'Surface runoff',color:COLORS.m1},{key:'glacier_melt_mm',label:'Direct glacier melt',color:COLORS.m3}]} unit="mm/month" title="M4: where does simulated river water come from?"/><p className="cs-note">Snowmelt feeds the surface and groundwater pathways. Adding snowmelt again would double-count water.</p></>}
    {view==='snow'&&<><Chart rows={data.process_checks.snow_pairs} fields={[{key:'satellite_snow_percent',label:'MODIS snow fraction',color:COLORS.m1},{key:'model_snow_proxy_percent',label:'M4 three-zone snow proxy',color:COLORS.m3}]} unit="%" title="Does the model retain snow in the right months?"/><p className="cs-note">{data.process_checks.snow_scores.n} pairs; descriptive RMSE {fmt(data.process_checks.snow_scores.rmse)} percentage points. A whole elevation zone counts as snow covered when its SWE exceeds 1 mm; MODIS measures a finer fractional pattern. This is a coarse process check.</p></>}
    {view==='et'&&<><Chart rows={data.process_checks.et_pairs} fields={[{key:'mod16_et_mm',label:'MOD16 terrestrial ET',color:COLORS.m1},{key:'model_et_mm',label:'M4 basin ET',color:COLORS.m4}]} unit="mm/month" title="Is the simulated water loss plausible?"/><p className="cs-note">{data.process_checks.et_scores.n} pairs; descriptive RMSE {fmt(data.process_checks.et_scores.rmse)} mm/month. Valid terrestrial pixels and whole-basin estimates have different spatial support; these are not ground-truth ET measurements.</p></>}
    <details><summary>What changed from the thesis, and what is still missing?</summary><div className="cs-table-wrap"><table><thead><tr><th>Method</th><th>Thesis pages</th><th>Status</th><th>Current implementation</th></tr></thead><tbody>{data.method_gap_matrix.map(r=><tr key={r.method}><td>{r.method}</td><td>{r.thesis_pages}</td><td>{r.status}</td><td>{r.implementation}</td></tr>)}</tbody></table></div></details>
    <details><summary>Check the equations, fitted parameters and assumptions</summary><p>All internal fluxes use millimetres. SCS retention is 25400/CN − 254 mm; runoff stays zero below 0.2 times retention. Groundwater release is (1 − retention) times yesterday’s store. Actual ET is capped by available soil water. Maximum conservation residual: {Math.max(...data.models.map(m=>m.max_abs_mass_balance_residual_mm)).toExponential(2)} mm/day.</p><div className="cs-table-wrap"><table><thead><tr><th>Model</th><th>Precipitation multiplier</th><th>Soil capacity · mm</th><th>Daily groundwater retention</th><th>Crop coefficient</th><th>CN offset</th><th>Fit status</th></tr></thead><tbody>{data.models.map(m=><tr key={m.key}><td>{m.key.toUpperCase()}</td>{Object.values(m.parameters).map((v,i)=><td key={i}>{fmt(v,i===2?4:2)}</td>)}<td>{m.optimizer.success?'Search converged':'Search budget reached'}{m.parameters_at_bounds.length?`; near bounds: ${m.parameters_at_bounds.join(', ')}`:''}</td></tr>)}</tbody></table></div><ul>{data.assumptions.map(t=><li key={t}>{t}</li>)}</ul></details>
    <details><summary>Which assumptions change the result?</summary><p>Each change starts from M4’s frozen calibration. These are sensitivity experiments, not causal importance or uncertainty intervals.</p><div className="cs-table-wrap"><table><thead><tr><th>Changed assumption</th><th>Mean flow change</th><th>RMSE change · m³/s</th></tr></thead><tbody>{data.sensitivity.map(r=><tr key={r.scenario}><td>{r.scenario}</td><td>{fmt(r.mean_flow_change_percent)}%</td><td>{fmt(r.rmse_change_cms)}</td></tr>)}</tbody></table></div></details>
    <div className="cs-section-head"><div><span className="cs-eyebrow">CHAPTER 3 / CONDITIONAL SCENARIOS</span><h3>How could the timing of water change?</h3></div><div className="cs-controls"><label>Model structure<select aria-label="Thesis climate scenario model" value={scenarioModel} onChange={e=>setScenarioModel(e.target.value)}><option value="m4">M4 · elevation and CN</option><option value="m3">M3 · lumped CN</option></select></label></div></div>
    <Chart rows={scenarioRows} fields={scenarios.map((r,i)=>({key:`s${i}`,label:r.scenario,color:['#dce8ed','#58c9e5','#edb06c','#baa5ef','#a9cd7e'][i]}))} unit="m³/s" title="Climate stress tests: the same daily sequence under changed conditions"/>
    <p className="cs-note">{data.climate_scenario_note}</p>
    <details><summary>Observed monthly trends and their limits</summary><p>Sen’s slope describes how much monthly mean discharge changes per year. Holm p-values account for twelve monthly tests; serial dependence remains unresolved, so these results are exploratory.</p><div className="cs-table-wrap"><table><thead><tr><th>Month</th><th>Years</th><th>Slope · m³/s/year</th><th>Nominal 95% interval</th><th>Holm p-value</th></tr></thead><tbody>{data.monthly_trends.map(r=><tr key={r.month}><td>{MONTHS[r.month-1]}</td><td>{r.years}</td><td>{fmt(r.sen_slope_cms_year)}</td><td>{fmt(r.slope_lower95)} to {fmt(r.slope_upper95)}</td><td>{fmt(r.p_holm,3)}</td></tr>)}</tbody></table></div></details>
    <p className="cs-note">The thesis gauge coordinate is {fmt(data.gauge_audit.coordinate_separation_m/1000)} km from ours. Gauge identity and drainage area still require confirmation. Land-cover accuracy: {data.classification_accuracy.n} independently labelled samples; {data.classification_accuracy.overall_accuracy==null?'accuracy remains unmeasured':`${fmt(data.classification_accuracy.overall_accuracy*100)}% sample accuracy`}. Completion of these experiments does not turn the readiness bar green.</p>
    <div className="cs-hero-actions">{[['sabitov-methods-atlas.pdf','Six-page scientific atlas'],['sabitov-methods-analysis.xlsx','Results & chart data'],['sabitov-methods.json','Methods, parameters & hashes'],['sabitov-daily-predictions.csv','Daily predictions']].map(([file,label])=><a key={file} href={BASE+file} download>{label} ↗</a>)}</div>
  </section>;
}
